# Generated by Django 4.2.4 on 2023-08-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iniciosesion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="admin",
            table="Administrador",
        ),
    ]
